spring.application.name = E-Go
spring.datasource.url=jdbc:mysql://localhost:3306/e_go
spring.datasource.username=root
spring.datasource.password=@Kienxs1s
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true